### PR TITLE
StreamSeekableInput wrapper for InputStreams

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
Example which wraps a `SeekableInput` where I'd like to use this to wrap an `InputStream`: https://github.com/palantir/hadoop-crypto/blob/develop/crypto-core/src/main/java/com/palantir/crypto2/io/CryptoStreamFactory.java#L47

**Comment by ellisjoe** [comment]
FWIW this is what apache does as well: https://github.com/apache/commons-crypto/blob/master/src/main/java/org/apache/commons/crypto/stream/input/StreamInput.java

**Comment by markelliot** [comment]
I think it's a little weird that we're accepting a SeekableInput (and thus would assume that we have efficient seek), but then UOE on calls to seek. What if we retool our code to accept an InputStream (because apparently we do not need a SeekableInput, and make it possible to translate the other way?

**Comment by ellisjoe** [comment]
Agree this is weird, but having a second code path where you plumb through an InputStream everywhere there was previously a SeekableInput is worse. The use case here is that I'd like to decrypt streams of bytes, sometimes those streams are seekable and sometimes there not. So I need the following two methods:
```
SeekableInput decrypt(SeekableInput, KeyMaterial)
InputStream decrypt(InputStream, KeyMaterial)
```
The second is easy to implement if I have this wrapper: https://github.com/palantir/hadoop-crypto/pull/129/files

Maybe it just makes sense to leave this as a private class in the other project.

**Comment by markelliot** [comment]
I'd prefer the private class because the SeekableInput that eats an InputStream cannot actually fulfill the API and will lead to very bad assumptions.

**Comment by markelliot** [comment]
the other thing I'm pretty confused about is that clearly your method does not _need_ a SeekableInput

**Comment by markelliot** [comment]
...so perhaps instead of eating a SeekableInput, the primary method should eat a InputStream, and going SeekableInput -> InputStream _is_ safe.

**Comment by ellisjoe** [comment]
the method doesn't _need_ to be a seekable input to do decryption, but it needs to take a seekable input if you want the returned stream to be seekable

**Pull request closed without merging**
